# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  dir:  # id of input
    description: 'List of files'
    required: true
    default: './'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
